services:
  suricata-notify:
    image: w1ltshire/suricata-notify:latest
    container_name: suricata-notify
    restart: always
    volumes:
      - /home/corruptmemory/misc/temp/eve.json:/etc/eve.json
      - ./config.toml:/etc/suricata-notify.toml
